# Generated by Django 5.0.1 on 2024-04-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dish', verbose_name='блюдо')),
            ],
            options={
                'verbose_name': 'покупатель',
                'verbose_name_plural': 'покупатели',
            },
        ),
    ]
