# Generated by Django 5.0.1 on 2024-04-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dish_is_active_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='название'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_version', models.CharField(max_length=50, verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=100, verbose_name='Название версии')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая версия')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
